### ISSUE TITLE
Local docker build fails

### ISSUE THREAD

**Issue by toastie89** [borgmatic-collective/docker-borgmatic#170]
I've tried to build the docker [base](https://github.com/borgmatic-collective/docker-borgmatic/tree/master/base) image locally with Docker version 20.10.20 and ran into several errors:

#### 1st try
```sh
docker build .
#dockerfile parse error line 32: Unknown flag: link
```

#### 2nd try
I have added `# syntax=docker/dockerfile:1.4` on top of the [Dockerfile](https://github.com/borgmatic-collective/docker-borgmatic/blob/master/base/Dockerfile).

```sh
DOCKER_BUILDKIT=1 docker build .
#13 38.31       test compiling /tmp/tmp_ruamel_c7_6zu3m/test_ruamel_yaml.c -> test_ruamel_yaml compile error: /tmp/tmp_ruamel_c7_6zu3m/test_ruamel_yaml.c
#13 38.31       Exception: command 'gcc' failed: No such file or directory
```

Is there anything more to consider when building the image? I would appreciate your help :-)

**Comment by toastie89** [comment]
I've tried to build with github actions resulting in the same error:
https://github.com/toastie89/docker-borgmatic/actions/runs/3297196717/jobs/5437725071

**Comment by toastie89** [comment]
By adding back `gcc` and `alpine-sdk`, the build works fine. From #148 I found that wheels are build, still there is apparently some compilation needed?

**Comment by psi-4ward** [comment]
Can one explain this?

**Comment by toastie89** [comment]
@psi-4ward, do you see the same issue, or is it only me?

**Comment by psi-4ward** [comment]
Yes same here. Look at my fork

**Comment by grantbevis** [comment]
I get the same when building the image on NixOS + podman.

@modem7 any ideas bud

**Comment by modem7** [comment]
Hey guys, 

Just investigating on my end now.

@grantbevis - we should probably set up a github action for issue assignment otherwise there are no notifications and users get left in limbo for a while. 

- With regard to --link, that shouldn't be a problem if built with buildx as our github actions do (which uses Buildkit by default), although it should have `# syntax = docker/dockerfile:latest` at the top of the Dockerfile realistically (have tested without and no issues).

- With regard to the build, it looks like ruamel.yaml.clib was updated from 0.2.6 to 0.2.7, and borg(matic) doesn't strictly pin the versions (ruamel.yaml.clib>=0.2.6). I'll get our Pypi index updated now.

- @grantbevis python:3.11.0-alpine3.16 has just been released. I'd suggest us updating the Dockerfiles to reflect lest we add more maintenance work by having to build for cp10 and cp11.

Let me get a pypi build made for that now.

**Comment by modem7** [comment]
Github actions are now building the github pages for the pypi index now, should be good to go once it's done.

**Comment by modem7** [comment]
Can confirm current build is now working with the following command:

```shell
docker buildx build --rm=true --compress --no-cache --build-arg BUILDKIT_INLINE_CACHE=1 --platform linux/amd64,linux/arm64 -t borg:test https://github.com/borgmatic-collective/docker-borgmatic.git#:base
```
