### ISSUE TITLE
Remove lock on SIGTERM

### ISSUE THREAD

**Issue by tnyeanderson** [borgmatic-collective/docker-borgmatic#85]
Currently, if I restart the host in the middle of a backup, borgmatic can't perform any backups until I manually intervene by removing the lock.

If the host gets restarted or the docker container goes down, the lock stays in place. We can account for at least some of this by removing the lock on SIGTERM if the lock belongs to us.

https://blog.knoldus.com/signals-handling-inside-docker-container/

After checking if the lock is because of us (not sure how to do this yet) run:
`borgmatic borg break-lock`

This will make it so borgmatic can start working immediately once the container comes back up.

**Comment by b3vis** [comment]
Good idea, I feel that we need to tread carefully here because if someone's backup has crashed halfway through and the container restarts we don't want it to just re-try again because the repository could be corrupt. This is when you'd then run consistency checks on your repo.

Happy for you to work on this and submit a PR but this isn't something I'd look to implement myself.

**Comment by tnyeanderson** [comment]
You raise a good point about running a consistency check... I will have to look deeper into the inner workings of borg to see if this would be an issue. I would think that consistency checks are run whenever a backup is attempted, though I could be wrong. I might also argue that *trying* to back up against a possibly corrupt repo still provides a better chance of a successful backup than never trying at all due to a stale lock :)

I will do some investigating and see what I come up with. Thanks for your insight and your great work on this repo! :)
